### PR TITLE
Bazel updates for Garden build

### PR DESCRIPTION
**Pull request by mjcarroll**
Updates bazel build for gazebo garden vesions.  Also cleans up a few places where we were hardcoding Cmake variables.

### CODE REVIEW

**Comment by mjcarroll** [comment]
@azeey this is ready for another look

**Comment by azeey** [comment]
I'm getting an error
```
$ bazel build //...
ERROR: Traceback (most recent call last):
        File "/home/addisuzt/ws/gz-bazel-src/sdformat/BUILD.bazel", line 6, column 6, in <toplevel>
                "add_lint_tests",
Error: file '@gz//bazel/skylark:build_defs.bzl' does not contain symbol 'add_lint_tests'
ERROR: package contains errors: sdformat
ERROR: package contains errors: sdformat: Traceback (most recent call last):
        File "/home/addisuzt/ws/gz-bazel-src/sdformat/BUILD.bazel", line 6, column 6, in <toplevel>
                "add_lint_tests",
Error: file '@gz//bazel/skylark:build_defs.bzl' does not contain symbol 'add_lint_tests'
ERROR: Skipping '//...': Error evaluating '//...': error loading package 'sdformat': Package 'sdformat' contains errors
WARNING: Target pattern parsing failed.
ERROR: Error evaluating '//...': error loading package 'sdformat': Package 'sdformat' contains errors
INFO: Elapsed time: 0.562s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (78 packages loaded)

```

I followed the instructions in the `gz-bazel` repo. Not sure if I'm doing something wrong.

**Comment by mjcarroll** [comment]
That's my fault. I also updated a gz_bazel rule in a branch today.  Will
let you know when it's ready again.

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by mjcarroll** [comment]
@azeey I think this one is ready for another look

**Review by iche033 — APPROVED** [review]

**Pull request merged**
