### PR TITLE
Merge sdf9 ➡️  sdf12

### PR DESCRIPTION
**Pull request by azeey**
# ➡️  Forward port

Port `sdf9 ` ➡️  `sdf12`

Branch comparison: https://github.com/gazebosim/sdformat/compare/sdf12...sdf9

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by iche033 — APPROVED** [review]

**Comment by azeey** [comment]
@j-rivero There's a new cmake warning in the homebrew build, I think because `psutil` is not being installed anymore.

**Comment by azeey** [comment]
I'll go ahead and merge since this isn't the cause for the homebrew warning on Jenkins.

**Comment by scpeters** [comment]
> @j-rivero There's a new cmake warning in the homebrew build, I think because `psutil` is not being installed anymore.

the need to install this pip package has historically been encoded in [sdformat-default-devel-homebrew-amd64.bash](https://github.com/gazebo-tooling/release-tools/blob/37e22107c76c49e2575f799a035bb60243aa276e/jenkins-scripts/sdformat-default-devel-homebrew-amd64.bash#L7), but I believe this script is no longer being called as part of #1010

would it be better to add a `.github/ci/macos_requirements.txt` file with needed `pip` packages similar to the `.github/ci/packages.apt` file and then update the [project-default-devel-homebrew-amd64.bash](https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash) script to look for that file and install those packages?

**Comment by j-rivero** [comment]
> @j-rivero There's a new cmake warning in the homebrew build, I think because `psutil` is not being installed anymore.

Ouch, I think that this is a regression introduced while migrating to `gz-collections.yaml`. Should be fixed by https://github.com/gazebo-tooling/release-tools/pull/1072

**Comment by azeey** [comment]
> > @j-rivero There's a new cmake warning in the homebrew build, I think because `psutil` is not being installed anymore.
> 
> Ouch, I think that this is a regression introduced while migrating to `gz-collections.yaml`. Should be fixed by [gazebo-tooling/release-tools#1072](https://github.com/gazebo-tooling/release-tools/pull/1072)

That PR seems to be removing cmake warnings from Jenkins. I thought having the warning was useful since it notified us that `psutil` was not installed. My understanding is that before the recent gz-collection changes, it used to be installed, and now it's not, which is what's causing the warnings.

**Comment by j-rivero** [comment]
> My understanding is that before the recent gz-collection changes, it used to be installed, and now it's not, which is what's causing the warnings.

The gz-collection,yaml changes affects the way of generating the Jenkins jobs and how that Jenkins job configuration is being generated. It should not affect the way of provisioning the CI nodes (in this case Mac nodes for Brew) . The gz-collection.yaml migration should not impact (and hardly can do it) the software/dependencies installed.

> I thought having the warning was useful since it notified us that `psutil` was not installed.

Might have been useful in this case if you think that having `psutil` on Mac is useful. Until we can explicitly enforce using `gz-cmake` what dependencies we really require to be in a build it is hard to known which optional support we expect to find or which one we don't have interest into or it is not viable, specially on Windows/Mac.

**Comment by azeey** [comment]
I have no strong opinion on whether `psutil` is useful on Mac or not. I was just pointing out that this is changing behavior from what we were doing since the dependency was explicitly included in https://github.com/gazebo-tooling/release-tools/blob/37e22107c76c49e2575f799a035bb60243aa276e/jenkins-scripts/sdformat-default-devel-homebrew-amd64.bash#L7. If we no longer need to run the `psutil` tests on Mac, that's okay with me.

**Comment by j-rivero** [comment]
> I was just pointing out that this is changing behavior from what we were doing since the dependency was explicitly included in https://github.com/gazebo-tooling/release-tools/blob/37e22107c76c49e2575f799a035bb60243aa276e/jenkins-scripts/sdformat-default-devel-homebrew-amd64.bash#L7. If we no longer need to run the `psutil` tests on Mac, that's okay with me.

Understood. It is a regression since we are provisioning software in the CI scripts. I'll fix that.

**Comment by scpeters** [comment]
> would it be better to add a `.github/ci/macos_requirements.txt` file with needed `pip` packages similar to the `.github/ci/packages.apt` file and then update the [project-default-devel-homebrew-amd64.bash](https://github.com/gazebo-tooling/release-tools/blob/master/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash) script to look for that file and install those packages?

this is another option

**Pull request merged**
