### PR TITLE
ign -> gz : Remove redundant namespace references

### PR DESCRIPTION
**Pull request by methylDragon**
Part of: https://github.com/gazebo-tooling/release-tools/issues/784

### CODE REVIEW

**Comment by scpeters** [comment]
I think the namespace reduction plan in https://github.com/gazebo-tooling/release-tools/issues/784 is useful for eliminating `ignition::` namespaces, but for this library it is just removing `sdf::` in lots of places, which looks like noise to me. I would rather just decline this.

**Review by chapulina — APPROVED** [review]
This PR isn't strictly helpful for the `ignition` migration because this repository doesn't release any code under that namespace, so we shouldn't be `using namespace ignition` here. 

But I think removing those redundant namespaces doesn't hurt, makes some liner shorter, and the code a bit cleaner. It may just introduce some confusion for functions that aren't clearly from this library, like `sdf::split`

**Comment by chapulina** [comment]
I just saw @scpeters 's comment, I'm fine declining this PR if that's preferred.

**Comment by methylDragon** [comment]
I have no preferences, but if needed, I can exclude stuff like `split` from the cleanup, it's not too difficult for me to do (like a 5-10 min job)

**Comment by chapulina** [comment]
@methylDragon , I'll just close this one for expediency. We don't need to put more time into it. Let's focus on `ignition::` and `ignition::gazebo`.

**Pull request closed without merging**
