### PR TITLE
Bumps in Ionic: sdformat15

### PR DESCRIPTION
**Pull request by azeey**
Part of https://github.com/gazebo-tooling/release-tools/issues/1027

### CODE REVIEW

**Comment by iche033** [comment]
I think the homebrew build needs a sdformat15.rb formula?

**Comment by scpeters** [comment]
> I think the homebrew build needs a sdformat15.rb formula?

there wasn't an sdformat15 Alias, so maybe the script failed

**Comment by azeey** [comment]
https://github.com/osrf/homebrew-simulation/pull/2465

I guess the `bump_dependency.bash` script wants all `main` branches bumped first, which includes creating aliases in Homebrew.  I thought we could just run the script, which would hopefully create the formula and do the bumps in the same go. Since that doesn't seem to be working well, I suggest we merge all the bump PRs first. I'll create the aliases for Homebrew.

**Comment by azeey** [comment]
I was wondering why the macOS Github Action passed. There's a hardcoded `sdformat14` in workflow file, so it was using that formula.

**Review by iche033 — APPROVED** [review]

**Pull request merged**
