### PR TITLE
12 ➡️ 13 (main)

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️ Forward port

Port `sdf12` to `main`

Branch comparison: https://github.com/ignitionrobotics/sdformat/compare/main...sdf12

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by azeey — APPROVED** [review]

**Comment by scpeters** [comment]
looks like an accidental squash-merge

**Comment by chapulina** [comment]
> looks like an accidental squash-merge

Are you sure? f3c2704b402015d30e5ec59cb127eade6d36fabd has 2 parents, I see the individual PR commits in https://github.com/gazebosim/sdformat/commits/main and they're not on the comparison anymore: https://github.com/gazebosim/sdformat/compare/main...sdf12

**Comment by scpeters** [comment]
> > looks like an accidental squash-merge
> 
> Are you sure? [f3c2704](https://github.com/gazebosim/sdformat/commit/f3c2704b402015d30e5ec59cb127eade6d36fabd) has 2 parents, I see the individual PR commits in https://github.com/gazebosim/sdformat/commits/main and they're not on the comparison anymore: [main...sdf12](https://github.com/gazebosim/sdformat/compare/main...sdf12)

yeah you're right it was a merge commit. it just looked like a squash merge because the commit message in https://github.com/gazebosim/sdformat/commit/f3c2704b402015d30e5ec59cb127eade6d36fabd is a mile long

sorry for the noise

**Comment by chapulina** [comment]
> the commit message in https://github.com/gazebosim/sdformat/commit/f3c2704b402015d30e5ec59cb127eade6d36fabd is a mile long

So, I still don't understand how GitHub populates the default commit title and commit message. I seem to get one of various patterns each time. When it's a forward-port and it has all commits listed like that, I leave it like that. But it doesn't do that every time 🤷🏽‍♀️

**Pull request merged**
