### PR TITLE
[vcpkg] remove absolute path

### PR DESCRIPTION
**Pull request by talregev**
remove absolute path.

### CODE REVIEW

**Comment by azeey** [comment]
There's some ongoing [work](https://github.com/gazebosim/gz-sim/issues/626) to make gazebo libraries relocatable. I believe the plan is to apply the same changes that were made in other libraries to libsdformat.

**Comment by traversaro** [comment]
Yes, a proper fix is to do here what have been done in other Gazebo libraries (see links in https://github.com/gazebosim/gz-sim/issues/626#issuecomment-1384638782), just removing the use of the hardcoded installation prefix may break existing workflows.

**Comment by talregev** [comment]
@azeey @traversaro 
Should I close this PR?

**Comment by azeey** [comment]
Yes, I think it's best to close this.

**Pull request closed without merging**
