### PR TITLE
Noise: update calls to use sdf::Errors parameters

### PR DESCRIPTION
**Pull request by marcoag**
Signed-off-by: Marco A. Gutierrez <marco@openrobotics.org>

# 🎉 New feature

Work towards https://github.com/gazebosim/sdformat/issues/820.

Depends on: https://github.com/gazebosim/sdformat/pull/1141.

## Summary
Adds missing `Errors` structure parameters in a few methods of the Noise class.

## Test it
Using the Noise class should report all errors through `sdf::Errors` if the `errors` parameter is used, it should print them otherwise.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by aaronchongth — APPROVED** [review]
LGTM!

**Review by aaronchongth — CHANGES_REQUESTED** [review]
Just noticed that there is `Noise_TEST.cc`, could you a few minimal tests for the function overload? Perhaps something similar to [`TEST(DOMNoise, ToElement)`](https://github.com/gazebosim/sdformat/blob/sdf13/src/Noise_TEST.cc#L224), and another where an expected error is returned

**Review by aaronchongth — APPROVED** [review]
Per DM, changes are small enough, more tests not required. LGTM!

**Comment by marcoag** [comment]
> Per DM, changes are small enough, more tests not required. LGTM!

Just went ahead and added a test, since the workload was not very heavy.

**Review by aaronchongth — APPROVED** [review]
Thanks for adding the test!

**Pull request merged**
