### PR TITLE
Param::Set: fix truncation of floating-point values

### LINKED ISSUE #1136: Param::Set truncates floating point numbers
## Environment
* OS Version: confirmed on Ubuntu / macOS
* Source or binary build? tested on `sdf13` branch
 
## Description
* Expected behavior: when passing a value containing floating point values to `Param::Set`, all the precision should be preserved
* Actual behavior: some precision is lost when using `Param::Set`

## Steps to reproduce

1. Check out and build https://github.com/gazebosim/sdformat/commit/f45d3710ac627cceeabd155e32b012d37f0ea477
2. Observe failure of test cases added to `UNIT_Param_TEST` demonstrating this bug

## Output

~~~
[ RUN      ] Param.Double
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:117: Failure
Expected equality of these values:
  sixteenDigits
    Which is: 12345678.876543211
  value
    Which is: 12345700
[  FAILED  ] Param.Double (0 ms)
[ RUN      ] Param.Vector3d
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:142: Failure
Expected equality of these values:
  0.0 + fifteenDigits
    Which is: 0.123456789012345
  value.X()
    Which is: 0.123457
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:143: Failure
Expected equality of these values:
  1.0 + fifteenDigits
    Which is: 1.123456789012345
  value.Y()
    Which is: 1.1234599999999999
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:144: Failure
Expected equality of these values:
  2.0 + fifteenDigits
    Which is: 2.1234567890123448
  value.Z()
    Which is: 2.1234600000000001
[  FAILED  ] Param.Vector3d (0 ms)
[ RUN      ] Param.Pose3d
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:176: Failure
Expected equality of these values:
  0.0 + fifteenDigits
    Which is: 0.123456789012345
  value.Pos().X()
    Which is: 0.123457
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:177: Failure
Expected equality of these values:
  1.0 + fifteenDigits
    Which is: 1.123456789012345
  value.Pos().Y()
    Which is: 1.1234599999999999
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:178: Failure
Expected equality of these values:
  2.0 + fifteenDigits
    Which is: 2.1234567890123448
  value.Pos().Z()
    Which is: 2.1234600000000001
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:179: Failure
Expected equality of these values:
  0.5 * fifteenDigits
    Which is: 0.061728394506172499
  value.Rot().Euler().X()
    Which is: 0.06172840000000001
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:180: Failure
Expected equality of these values:
  1.0 * fifteenDigits
    Which is: 0.123456789012345
  value.Rot().Euler().Y()
    Which is: 0.123457
/Users/scpeters/ws/garden/src/sdformat/src/Param_TEST.cc:181: Failure
Expected equality of these values:
  2.0 * fifteenDigits
    Which is: 0.24691357802468999
  value.Rot().Euler().Z()
    Which is: 0.24691400000000005
[  FAILED  ] Param.Pose3d (0 ms)
~~~

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes #1136, #103

## Summary

As noted in #1136, the `Param::Set` API currently truncates floating point values, demonstrated by the failing test added in https://github.com/gazebosim/sdformat/commit/f45d3710ac627cceeabd155e32b012d37f0ea477. In https://github.com/gazebosim/sdformat/commit/1107f212efaabfc6769bc5f287f1ba22955c0003, the `ParamStreamer` helper is used in `Param::Set` with maximum digits to prevent truncation. The expected values in a test are adjusted in https://github.com/gazebosim/sdformat/commit/9ef6cd70248322265f3d110d497448eb698754b2 to expect more precision.

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by jennuine — COMMENTED** [review]
LGTM, I'll formally approve after the garden release so this doesn't accidentally get merged

**Comment by scpeters** [comment]
@iche033 I realized that this should also fix #103, which you reported long ago and added a test for. I've cherry-picked your test to this branch, but it doesn't have a sign-off message. Are you comfortable with amending that commit with your sign-off message on this branch?

**Comment by iche033** [comment]
just amended and signed off the last commit

**Comment by scpeters** [comment]
> LGTM, I'll formally approve after the garden release so this doesn't accidentally get merged

@jennuine we have a stable release of sdformat13, so I think we can start merging for 13.1

**Review by jennuine — APPROVED** [review]

**Pull request merged**
