### PR TITLE
Backport mesh optimization feature

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Backport

Backport mesh optimization related changes from #1382 and #1386

**Note to maintainers**: Remember to **Rebase and merge** with commit (not squash-merge)

### CODE REVIEW

**Comment by scpeters** [comment]
these changes also need python bindings

**Comment by scpeters** [comment]
> **Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

I think rebase-and-merge works well for backports

**Comment by scpeters** [comment]
> these changes also need python bindings

ticketed in https://github.com/gazebosim/sdformat/issues/1400

**Review by scpeters — APPROVED** [review]

**Review by scpeters — CHANGES_REQUESTED** [review]
can you include a backport of the python bindings in https://github.com/gazebosim/sdformat/pull/1398?

**Comment by scpeters** [comment]
> #1398

actually they were already added in https://github.com/gazebosim/sdformat/pull/1398

**Comment by iche033** [comment]
> actually they were already added in #1398

updated PR to include commit from #1398

**Comment by iche033** [comment]
> I think rebase-and-merge works well for backports

Updated PR description

**Review by scpeters — APPROVED** [review]

**Pull request merged**
