### PR TITLE
Allow empty strings in plugin and custom attributes

### LINKED ISSUE #725: Error when attributes in custom elements have empty values
## Environment
* OS Version: 
* Source or binary build? source, `sdf9`

## Description
* Expected behavior: Users should be able to use empty strings for the values of their custom attributes without any errors.
* Actual behavior: When attributes in custom or unrecognized elements have empty values, the parser emits an error stating that an empty string may not be used for a required parameter. 

Related: 
 * https://github.com/ignitionrobotics/sdformat/issues/20
 * https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/111/page/1

## Steps to reproduce

1. Save the following to a file and run `ign sdf -k <file name>`
```xml
<sdf version="1.7" xmlns:custom="http://example.org/schema">
  <world name="default">
    <custom:foo attr1=""/>
  </world>
</sdf>
```

## Output
```
Error [Param.cc:473] Empty string used when setting a required parameter. Key[attr1]
Error [Param.cc:473] Empty string used when setting a required parameter. Key[attr1]
Valid.
```

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes #725

## Summary

Currently errors are generated when adding an attribute containing an empty string to a `<plugin>` block or as a custom attribute. This adds failing tests in https://github.com/gazebosim/sdformat/commit/0637c210053ae3d1b98e9be55b30f9b3f1e3516f to confirm the bug and fixes the errors in https://github.com/gazebosim/sdformat/commit/e55a9e1a251b650ac0588e0e2b7323f0ca900961 by setting `_required == 0` when calling [Element::AddAttribute](https://github.com/gazebosim/sdformat/blob/6f1c36502f1085836ab9876e26afac3238f26820/include/sdf/Element.hh#L274-L300).

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [X] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by azeey — COMMENTED** [review]
Looks good, but can you check the output of `ToString()` to make sure the custom attribute is included? I seem to recall that was a problem.

**Comment by scpeters** [comment]
> Looks good, but can you check the output of `ToString()` to make sure the custom attribute is included? I seem to recall that was a problem.

ok, thanks for bringing that up. I updated `ElementPrivate::PrintAttributes` in https://github.com/gazebosim/sdformat/pull/1407/commits/a4f811f7fae269b77a8c35f16324340ce5f1f214 to always print custom attributes

Empty attributes in the `<plugin/>` element won't be printed by `ToString` unless they are in a custom xml namespace, as I've noticed with the following test patch:

~~~
diff --git a/test/integration/plugin_attribute.cc b/test/integration/plugin_attribute.cc
index 7f4f9f4c..b66c9da1 100644
--- a/test/integration/plugin_attribute.cc
+++ b/test/integration/plugin_attribute.cc
@@ -65,4 +65,9 @@ TEST(PluginAttribute, ParseAttributes)
     EXPECT_EQ(value->Get<std::string>(""),
               std::string("value"));
   }
+  {
+    auto pluginToString = plugin->ToString("");
+    EXPECT_NE(std::string::npos, pluginToString.find("empty_attribute=''"))
+      << pluginToString;
+  }
 }
~~~

I don't have a good idea for how to fix it, so I'd prefer to open an issue documenting that behavior and potentially close it as won't fix

**Review by azeey — APPROVED** [review]
LGTM! Opening an issue to document the behavior in `<plugin>` sounds good.

**Comment by scpeters** [comment]
> LGTM! Opening an issue to document the behavior in `<plugin>` sounds good.

opened a new issue: https://github.com/gazebosim/sdformat/issues/1421

**Pull request merged**
