### PR TITLE
Bump main to sdformat 16.0.0~pre1

### PR DESCRIPTION
**Pull request by caguero**
# 🎉 New feature

## Summary

Bump main to sdformat 16.0.0~pre1

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by iche033** [comment]
test fixing macOS github ci workflow: [e4a4c68](https://github.com/gazebosim/sdformat/pull/1487/commits/e4a4c687768fd78240ce7e4eec330ebbea4355e5)

**Comment by scpeters** [comment]
> test fixing macOS github ci workflow: [e4a4c68](https://github.com/gazebosim/sdformat/pull/1487/commits/e4a4c687768fd78240ce7e4eec330ebbea4355e5)

that is a good fix, but the problem appears to be that homebrew added `python@3.13` and our homebrew formula builds python bindings for gz-math8 with `python@3.12` (see [gz-math8.rb:23](https://github.com/osrf/homebrew-simulation/blob/master/Formula/gz-math8.rb#L23)), but now cmake is finding python 3.13 when searching for the interpreter so tests fail when they can't find the gz-math8 bindings

We've faced this before; I think we can hard-code which python version we want to find, let me see if I can find it

**Comment by scpeters** [comment]
> We've faced this before; I think we can hard-code which python version we want to find, let me see if I can find it

I think we need an adjustment to the `-DPython_EXECUTABLE=...` cmake arg to point to the version of python that we currently support

some homebrew formula build bindings for multiple versions of python, but that seems a bit complicated

**Comment by scpeters** [comment]
> > We've faced this before; I think we can hard-code which python version we want to find, let me see if I can find it
> 
> I think we need an adjustment to the `-DPython_EXECUTABLE=...` cmake arg to point to the version of python that we currently support
> 
> some homebrew formula build bindings for multiple versions of python, but that seems a bit complicated

I've opened https://github.com/osrf/homebrew-simulation/issues/2834 to track this issue

**Review by iche033 — APPROVED** [review]

**Comment by iche033** [comment]
the homebrew python issue is being addressed separately. Merging this in first.

**Pull request merged**
